# Generated by Django 5.0.3 on 2024-04-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_county_order_phone_number'),
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLinItem',
            new_name='OrderLineItem',
        ),
    ]
