# Generated by Django 5.0.3 on 2024-04-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_orderlinitem_orderlineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
